import * as pdfjsLib from "https://cdn.jsdelivr.net/npm/pdfjs-dist@6.2.108/build/pdf.mjs";
import {normativeCatalog,normativeRules,normativeSources} from "./normative-catalog.js";
pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdn.jsdelivr.net/npm/pdfjs-dist@6.2.108/build/pdf.worker.mjs";

const PASS="APROVADO",FAIL="REPROVADO",WARN="ALERTA",REVIEW="REVISÃO MANUAL",NA="NÃO APLICÁVEL";
const MM=72/25.4,pageRule=normativeRules["page.a4"],rectoRule=normativeRules["margin.recto"];
const A4=[pageRule.values.width_mm*MM,pageRule.values.height_mm*MM],TOL=pageRule.values.tolerance_pt??1.8,LEFT=rectoRule.values.left_mm*MM,RIGHT=rectoRule.values.right_mm*MM;
const $=s=>document.querySelector(s); let report=null;
const ck=(id,category,rule,source,status,evidence,correction="",mandatory=true,level="automático",normativeRule="",locator="",normativity="")=>({id,category,rule,source,status,evidence,correction,mandatory,level,normativeRule,locator,normativity});
const norm=s=>String(s||"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ").trim().toUpperCase();
const compact=s=>norm(s).replace(/[^A-Z0-9]/g,"");
const sourceLabel=ruleId=>normativeRules[ruleId].sources.map(id=>normativeSources[id].title).join(" / ");
const normSource=ruleId=>`${sourceLabel(ruleId)} · ${normativeRules[ruleId].locator}`;
const nck=(id,ruleId,category,label,status,evidence,correction="",mandatory=true,level="automático")=>{const r=normativeRules[ruleId];return ck(id,category,label,normSource(ruleId),status,evidence,correction,mandatory,level,ruleId,r.locator,r.normativity)};
const isTextFallback=s=>{const x=compact(s);return x.includes("TEXGYRETERMESX")||(x.includes("TEXGYRETERMES")&&!x.includes("MATH"))||x.includes("TEXGYREHEROS")};
const verdict=cs=>cs.some(c=>c.mandatory&&c.status===FAIL)?FAIL:cs.some(c=>c.mandatory&&c.status===REVIEW)?"REVISÃO NECESSÁRIA":cs.some(c=>[WARN,REVIEW].includes(c.status))?"APROVADO NOS CHECKS AUTOMÁTICOS, COM RESSALVAS":"APROVADO NOS CHECKS AUTOMÁTICOS";

function save(name,data,type){const b=new Blob([data],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
function csv(v){return `"${String(v??"").replaceAll('"','""')}"`}
function renderNormativeBase(){
 $("#norm-reviewed").textContent=normativeCatalog.reviewed_at;
 $("#norm-stats").textContent=`${normativeCatalog.rules.length} regras · ${normativeCatalog.sources.length} fontes versionadas`;
 const list=$("#norm-sources");list.replaceChildren();
 for(const source of normativeCatalog.sources){const li=document.createElement("li"),a=document.createElement(source.url?"a":"span");a.textContent=`${source.title} — ${source.status}`;if(source.url){a.href=source.url;a.target="_blank";a.rel="noopener"}li.append(a);list.append(li)}
}
function render(r){
 $("#summary").classList.remove("hidden");$("#report-section").classList.remove("hidden");$("#verdict").textContent=r.verdict;$("#file-name").textContent=r.file;$("#page-count").textContent=r.pages;
 const body=$("#report-body");body.replaceChildren();for(const c of r.checks){const tr=document.createElement("tr");for(const [i,v] of [c.status,c.category,c.rule,c.source,c.evidence,c.correction].entries()){const td=document.createElement("td");td.textContent=v;if(i===0)td.className=c.status===PASS?"status-pass":c.status===FAIL?"status-fail":c.status===WARN?"status-warn":"status-review";tr.append(td)}body.append(tr)}
 $("#counts").textContent=[PASS,FAIL,WARN,REVIEW,NA].map(s=>`${s}: ${r.checks.filter(c=>c.status===s).length}`).join(" · ");["#export-json","#export-csv","#print-report"].forEach(s=>$(s).disabled=false)
}

async function analyze(file,profile){
 const data=new Uint8Array(await file.arrayBuffer()),pdf=await pdfjsLib.getDocument({data}).promise,meta=await pdf.getMetadata(),outline=await pdf.getOutline(),js=await pdf.getJSActions().catch(()=>null);
 const pages=[],families=new Set();let tagged=false;
 for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n),vp=p.getViewport({scale:1}),tc=await p.getTextContent(),st=await p.getStructTree().catch(()=>null);if(st)tagged=true;for(const it of tc.items){const f=tc.styles?.[it.fontName]?.fontFamily;if(f)families.add(f)}pages.push({n,w:vp.width,h:vp.height,items:tc.items,text:tc.items.map(i=>i.str).join(" ").replace(/\s+/g," ")})}
 const cs=[ck("pdf.open","Integridade","PDF legível","Pré-requisito técnico",PASS,`${pdf.numPages} páginas processadas localmente.`)];
 const bad=pages.filter(p=>Math.abs(p.w-A4[0])>TOL||Math.abs(p.h-A4[1])>TOL).map(p=>p.n);cs.push(nck("layout.a4","page.a4","Layout","Papel A4",bad.length?FAIL:PASS,bad.length?`Páginas fora de A4: ${bad.join(", ")}`:"Todas as páginas em A4.",bad.length?"Configure A4 em todas as páginas.":""));
 const out=[];for(const p of pages)for(const i of p.items){const s=i.str?.trim();if(!s)continue;const x=i.transform[4],x1=x+(i.width||0),y=i.transform[5];if(/^\d+$/.test(s)&&y>p.h-75)continue;if(x<LEFT-TOL||x1>p.w-RIGHT+3)out.push([p.n,s.slice(0,20),x.toFixed(1),x1.toFixed(1)])}cs.push(nck("layout.margins","margin.recto","Layout","Margens horizontais do anverso: 3 cm / 2 cm",out.length?FAIL:PASS,out.length?`Exemplos: ${JSON.stringify(out.slice(0,8))}`:"Nenhum texto ultrapassa as margens.",out.length?"Recuar o elemento para dentro da mancha gráfica.":"",true,"geométrico"));
 const fam=[...families],fn=fam.map(compact),allowed=normativeRules["font.family.body"].values.allowed,keys=allowed.map(compact),lit=fam.filter((_,i)=>keys.some(k=>fn[i].includes(k))),fb=fam.filter(isTextFallback);let fs=lit.length&&!fb.length?PASS:fb.length&&!lit.length?(profile==="portable"?WARN:FAIL):REVIEW;const fontLabel=allowed.join(" ou ");cs.push(nck("font.family","font.family.body","Tipografia",`${fontLabel} literal`,fs,`Literais: ${lit.join(", ")||"nenhuma"}; fallback textual: ${fb.join(", ")||"nenhum"}.`,fs===PASS?"":`Use fonte-estrita=sim com ${fontLabel} e confirme no modo Deep/CLI.`,profile!=="portable","heurístico"));cs.push(ck("font.embedding","Tipografia","Todas as fontes incorporadas","PDF/A / preservação",REVIEW,"Web/Lite não certifica incorporação de todas as fontes.","Execute o modo Deep/CLI.",profile!=="portable","profundo"));
 const u=norm(pages.map(p=>p.text).join("\n")),req=[["cover","Capa","UNIVERSIDADE FEDERAL DO CEARA"],["approval","Folha de aprovação","BANCA EXAMINADORA"],["resumo","Resumo","RESUMO"],["abstract","Abstract","ABSTRACT"],["toc","Sumário","SUMARIO"],["refs","Referências","REFERENCIAS"]];for(const [id,label,t] of req){const ok=u.includes(t);cs.push(ck(`structure.${id}`,"Estrutura",label,"ABNT/UFC",ok?PASS:FAIL,ok?"Elemento localizado.":"Elemento não localizado.",ok?"":`Inclua ${label.toLowerCase()}.`))}
 for(const [id,t] of [["keywords","PALAVRAS-CHAVE"],["keywords-en","KEYWORDS"]]){const ok=u.includes(t),r=normativeRules["summary.paragraph"];cs.push(ck(`structure.${id}`,"Resumo",t,normSource("summary.paragraph"),ok?PASS:FAIL,ok?"Campo localizado.":"Campo ausente.",ok?"":`Inclua ${t.toLowerCase()}.`,true,"automático","summary.paragraph",r.locator,r.normativity))}
 const inf=meta.info||{},title=inf.Title||meta.metadata?.get?.("dc:title")||"",author=inf.Author||meta.metadata?.get?.("dc:creator")||"",lang=inf.Language||meta.metadata?.get?.("dc:language")||"";cs.push(ck("meta.lang","Metadados","Idioma principal","WCAG / preservação",lang?PASS:WARN,lang||"Não exposto pelo PDF.js.",lang?"":"Defina pt-BR.",false));cs.push(ck("meta.title","Metadados","Título do PDF","Boa prática de repositório",title?PASS:WARN,title||"Ausente.",title?"":"Defina o título PDF/XMP.",false));cs.push(ck("meta.author","Metadados","Autor do PDF","Boa prática de repositório",author?PASS:WARN,author||"Ausente.",author?"":"Defina o autor PDF/XMP.",false));
 const acc=profile==="accessibility";cs.push(ck("access.tagged","Acessibilidade","PDF estruturado/tagged","PDF/UA / WCAG",tagged?PASS:(acc?FAIL:WARN),tagged?"Árvore de estrutura detectada.":"Árvore de estrutura não detectada.",tagged?"":"Gere PDF tagged.",acc));cs.push(ck("access.bookmarks","Acessibilidade","Bookmarks","WCAG PDF2",outline?.length?PASS:WARN,outline?.length?`${outline.length} entradas de nível superior.`:"Não detectados.",outline?.length?"":"Adicione bookmarks.",false));cs.push(ck("security.javascript","Integridade","Sem JavaScript embutido","Preservação",js&&Object.keys(js).length?WARN:PASS,js&&Object.keys(js).length?"Ações JavaScript detectadas.":"Nenhuma ação JavaScript detectada.","",false));
 const pdfa=normativeRules["deposit.pdfa"].values.project_profile;cs.push(nck("pdfa.deep","deposit.pdfa","PDF/A",`Validação estrutural ${pdfa}`,REVIEW,"Web/Lite não substitui validação ISO completa.",`Execute o CLI/Deep com veraPDF -f 2b.`,profile!=="portable","profundo"));cs.push(nck("catalog.optional","deposit.catalog-card","Depósito UFC","Ficha catalográfica visual",NA,"Representação visual facultativa.","",false));cs.push(nck("approval.signatures","deposit.approval-signatures","Depósito UFC","Folha de aprovação sem assinaturas digitalizadas",REVIEW,"Exige inspeção visual.","Use a folha sem assinaturas no depósito.",false,"manual"));cs.push(nck("capes","deposit.capes","Depósito UFC","Agradecimento CAPES quando aplicável",REVIEW,"Depende do financiamento.","Inclua a redação obrigatória se aplicável.",false,"condicional"));
 if(acc){cs.push(ck("access.alt","Acessibilidade","Texto alternativo adequado","PDF/UA / WCAG",REVIEW,"Qualidade exige revisão humana.","Revise /Alt e artefatos decorativos.",true,"manual"));cs.push(ck("access.order","Acessibilidade","Ordem de leitura lógica","PDF/UA / WCAG",REVIEW,"Exige teste com tecnologia assistiva.","Revise a ordem de leitura.",true,"manual"))}
 return {file:file.name,pages:pdf.numPages,profile,verdict:verdict(cs),normativeCatalog:{schemaVersion:normativeCatalog.schema_version,reviewedAt:normativeCatalog.reviewed_at},checks:cs,mode:"web-lite-local",generatedAt:new Date().toISOString()};
}

renderNormativeBase();
$("#analyze").addEventListener("click",async()=>{const f=$("#pdf-file").files?.[0];if(!f)return alert("Selecione um PDF.");const b=$("#analyze");b.disabled=true;b.textContent="Validando...";try{report=await analyze(f,$("#profile").value);render(report)}catch(e){console.error(e);alert(`Falha na validação: ${e.message||e}`)}finally{b.disabled=false;b.textContent="Validar PDF"}});
$("#export-json").addEventListener("click",()=>report&&save("relatorio-validacao-ufc.json",JSON.stringify(report,null,2),"application/json;charset=utf-8"));
$("#export-csv").addEventListener("click",()=>{if(!report)return;const h=["Status","Categoria","Regra","Fonte","Evidência","Como corrigir","Nível","Obrigatório","Regra normativa","Localizador","Natureza"],rows=report.checks.map(c=>[c.status,c.category,c.rule,c.source,c.evidence,c.correction,c.level,c.mandatory?"sim":"não",c.normativeRule,c.locator,c.normativity]),data=[h,...rows].map(r=>r.map(csv).join(",")).join("\r\n");save("relatorio-validacao-ufc.csv",`\ufeff${data}`,"text/csv;charset=utf-8")});
$("#print-report").addEventListener("click",()=>window.print());
